# Generated by Django 5.2.4 on 2025-07-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(help_text='Font Awesome: "fas fa-laptop-code" atau Emoji: "🎨"', max_length=50),
        ),
    ]
