# Generated by Django 5.2.4 on 2025-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_aboutcontent_companyvalue_teammember_missionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Contoh: "100+", "24/7", "5+"', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistik',
                'verbose_name_plural': 'Statistik',
                'ordering': ['order'],
            },
        ),
    ]
